<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:include filename="$(find fishbot_description)/urdf/fishbot/common_inertial.xacro"/>
   
 
    <xacro:macro name="base_xacro" params="length radius">
        
        <link name="base_footprint">
            
        </link>
        <!--机器人的身体部分-->
        <link name="base_link">
            <!--部件的外观描述-->
            <visual name="base_visual">
            <!--沿着自己几何中心的偏移和旋转量-->
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <!--几何形状-->
                <geometry>
                    <!--圆柱体 radius 半径0.1m 高度 0.12m-->
                    <cylinder radius="${radius}" length="${length}"/>
                </geometry>
                <!--材质颜色-->
                <material name="white">
                    <color rgba="1.0 1.0 1.0 0.5"/>
                </material>
            </visual>
            <collision>
            <!--沿着自己几何中心的偏移和旋转量-->
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <!--几何形状-->
                <geometry>
                    <!--圆柱体 radius 半径0.1m 高度 0.12m-->
                    <cylinder radius="${radius}" length="${length}"/>
                </geometry>
                <!--材质颜色-->
                <material name="white">
                    <color rgba="1.0 1.0 1.0 0.5"/>
                </material>
            </collision>

            <xacro:cylinder_interia m="1.0" r="${radius}" h="${length}"/>
        </link>


        <joint name="joint_name" type="fixed">
            <origin xyz="0.0 0.0 ${length/2.0+0.032-0.001}" rpy="0.0 0.0 0.0"/>
            <parent link="base_footprint"/>
            <child link="base_link"/>
        </joint>
    </xacro:macro>
</robot>